### ISSUE TITLE
Incorrect example of usage

### ISSUE THREAD

**Issue by dakrone** [Bruce-Connor/org-agenda-property#2]
In the readme:

"If you installed manually, just make sure it's in your load-path and call"

```
(require 'smart-mode-line)
```

Maybe it was copied from the smart-mode-line repo and wasn't updated?

**Comment by Bruce-Connor** [comment]
Pretty much. And it's been there a long time. :-)
I'll fix it tomorrow.

**Comment by Malabarba** [comment]
Done. Thanks for filing.
